### ISSUE TITLE
Does this work in React-Native?

### ISSUE THREAD

**Issue by krishnaff** [tjmehta/graphql-fetch#6]
Hello, 

Trying to use this in RN (on iOS) and it throws an error:
`Unable to resolve module 'assert' from 'node_modules/graphql-fetch/index.js': Module does not exist in the module map`

Tried deleting nodemodules, reinstalling and clearing cache etc. Nothing works. 
Any pointers please?

**Comment by tjmehta** [comment]
I haven’t tried it with RN, but I can give it a try later today. What
version of RN are you using?

**Comment by krishnaff** [comment]
Hello, 
I just created a new app using `create-react-native-app` and it created the project with the following dependencies in package.json:
```
"dependencies": {
  "expo": "^20.0.0",
  "graphql-fetch": "^1.0.1",
  "react": "16.0.0-alpha.12",
  "react-native": "^0.47.0"
}
```

**Comment by tjmehta** [comment]
As far as I know it should work with RN
